# Generated by Django 3.2.7 on 2023-02-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('gst', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainInformation',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mr_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('narration', models.TextField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='bilti.party')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('date', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_destination', models.CharField(max_length=100)),
                ('no_of_packages', models.IntegerField()),
                ('weight', models.FloatField()),
                ('price_per_weight', models.FloatField()),
                ('amount', models.FloatField()),
                ('exp_date_of_delivery', models.DateField()),
                ('total_amount_with_gst', models.FloatField()),
                ('from_destination', models.CharField(max_length=100)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='bilti.party')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='bilti.party')),
                ('train_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilti.traininformation')),
            ],
        ),
    ]
