# Generated by Django 3.2.7 on 2023-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gr_number',
            field=models.IntegerField(default=0),
        ),
    ]
