# Generated by Django 3.2.7 on 2023-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilti', '0002_bill_gr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
